# Kustomization file for base Kubernetes resources
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ecommerce-platform-base
  annotations:
    description: "Base Kubernetes resources for E-Commerce Platform"

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: ecommerce-platform
  app.kubernetes.io/managed-by: kustomize
  project: azure-ecommerce-platform

# Common annotations applied to all resources
commonAnnotations:
  deployment.kubernetes.io/revision: "1"
  config.kubernetes.io/origin: "base"

# Namespace for all resources
namespace: ecommerce-platform

# Resource files to include
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - secrets.yaml
  - product-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - notification-service.yaml
  - frontend-service.yaml
  - api-gateway.yaml
  - ingress.yaml

# Images to be used (these will be updated by CI/CD)
images:
  - name: PLACEHOLDER_ACR_NAME.azurecr.io/product-service
    newTag: latest
  - name: PLACEHOLDER_ACR_NAME.azurecr.io/order-service
    newTag: latest
  - name: PLACEHOLDER_ACR_NAME.azurecr.io/payment-service
    newTag: latest
  - name: PLACEHOLDER_ACR_NAME.azurecr.io/notification-service
    newTag: latest
  - name: PLACEHOLDER_ACR_NAME.azurecr.io/frontend-service
    newTag: latest

# Configuration transformations
configurations:
  - kustomizeconfig.yaml

# Patches to apply
patchesStrategicMerge: []

# JSON patches
patches: []

# Replicas configuration (can be overridden in overlays)
replicas:
  - name: product-service
    count: 2
  - name: order-service
    count: 2
  - name: payment-service
    count: 2
  - name: notification-service
    count: 2
  - name: frontend-service
    count: 3
  - name: api-gateway
    count: 3

# Generate ConfigMap and Secret names with suffixes
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: ecommerce-platform
  annotations:
    note: "Generated by Kustomize"

# Variables that can be substituted
vars: []

# OpenAPI schema validation
openapi:
  path: "https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json"