# Secret template for application secrets
# Note: This template should be used with tools like Helm, Kustomize, or Azure Key Vault Provider
# Actual secret values should be injected at deployment time
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce-platform
  labels:
    app.kubernetes.io/name: ecommerce-platform
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # Database credentials (these should be injected from Azure Key Vault)
  COSMOS_DB_CONNECTION_STRING: "PLACEHOLDER_COSMOS_CONNECTION"
  SQL_SERVER_CONNECTION_STRING: "PLACEHOLDER_SQL_CONNECTION"
  
  # Service Bus credentials
  SERVICE_BUS_CONNECTION_STRING: "PLACEHOLDER_SERVICEBUS_CONNECTION"
  EVENT_HUB_CONNECTION_STRING: "PLACEHOLDER_EVENTHUB_CONNECTION"
  
  # Application Insights
  APPLICATIONINSIGHTS_CONNECTION_STRING: "PLACEHOLDER_APPINSIGHTS_CONNECTION"
  
  # JWT Secret for authentication
  JWT_SECRET: "PLACEHOLDER_JWT_SECRET"
  
  # Redis connection
  REDIS_CONNECTION_STRING: "PLACEHOLDER_REDIS_CONNECTION"
  
  # Payment service secrets
  PAYMENT_PROCESSOR_API_KEY: "PLACEHOLDER_PAYMENT_KEY"
  
  # Email service secrets
  SENDGRID_API_KEY: "PLACEHOLDER_SENDGRID_KEY"
  
  # Storage account key
  AZURE_STORAGE_CONNECTION_STRING: "PLACEHOLDER_STORAGE_CONNECTION"
---
# External Secret for Azure Key Vault integration
# This uses the Azure Key Vault Provider for Secrets Store CSI Driver
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: ecommerce-platform
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityClientID: "PLACEHOLDER_MANAGED_IDENTITY_CLIENT_ID"
    keyvaultName: "PLACEHOLDER_KEYVAULT_NAME"
    objects: |
      array:
        - |
          objectName: cosmos-db-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: sql-server-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: service-bus-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: event-hub-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: applicationinsights-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: jwt-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: redis-connection-string
          objectType: secret
          objectVersion: ""
        - |
          objectName: payment-processor-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: sendgrid-api-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: azure-storage-connection-string
          objectType: secret
          objectVersion: ""
    tenantId: "PLACEHOLDER_TENANT_ID"
  secretObjects:
  - secretName: ecommerce-secrets
    type: Opaque
    data:
    - objectName: cosmos-db-connection-string
      key: COSMOS_DB_CONNECTION_STRING
    - objectName: sql-server-connection-string
      key: SQL_SERVER_CONNECTION_STRING
    - objectName: service-bus-connection-string
      key: SERVICE_BUS_CONNECTION_STRING
    - objectName: event-hub-connection-string
      key: EVENT_HUB_CONNECTION_STRING
    - objectName: applicationinsights-connection-string
      key: APPLICATIONINSIGHTS_CONNECTION_STRING
    - objectName: jwt-secret
      key: JWT_SECRET
    - objectName: redis-connection-string
      key: REDIS_CONNECTION_STRING
    - objectName: payment-processor-api-key
      key: PAYMENT_PROCESSOR_API_KEY
    - objectName: sendgrid-api-key
      key: SENDGRID_API_KEY
    - objectName: azure-storage-connection-string
      key: AZURE_STORAGE_CONNECTION_STRING