# Development environment resource overrides
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: ecommerce-platform
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: product-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG_MODE
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce-platform
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: order-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG_MODE
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: ecommerce-platform
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: payment-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG_MODE
          value: "true"
        - name: FLASK_ENV
          value: "development"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: ecommerce-platform
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: notification-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG_MODE
          value: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: ecommerce-platform
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: frontend-service
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: REACT_APP_API_URL
          value: "https://dev-api-ecommerce.example.com/api"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: ecommerce-platform
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"