# Production security configurations
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: product-service-pdb
  namespace: ecommerce-platform
  labels:
    app.kubernetes.io/name: product-service
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: product-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  namespace: ecommerce-platform
  labels:
    app.kubernetes.io/name: order-service
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: order-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  namespace: ecommerce-platform
  labels:
    app.kubernetes.io/name: payment-service
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-service-pdb
  namespace: ecommerce-platform
  labels:
    app.kubernetes.io/name: frontend-service
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: ecommerce-platform
  labels:
    app.kubernetes.io/name: api-gateway
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
---
# Network policy for production security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-network-policy
  namespace: ecommerce-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from nginx-ingress
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  # Allow inter-service communication
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: ecommerce-platform
  # Allow monitoring
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 9090
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow HTTPS to external services
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
  # Allow communication to Azure services
  - to: []
    ports:
    - protocol: TCP
      port: 1433  # SQL Server
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6380  # Redis SSL
  # Allow inter-service communication
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/part-of: ecommerce-platform